// LEVEL 20 (100)

// MARK: - PLAYERS

let ADELINE: Entity = .init(name: "Adeline",
                         hp: 25,
                         atk: 10,
                         exa: 30,
                         def: 20,
                         spd: 15,
                         summon: nil,
                         money: 100,
                         item: [],
                         abilities: [
                            .init(name: "Fire Shield",
                                  power: 0,
                                  pp: 5,
                                  attributes: [.protect]),
                            .init(name: "Rampion",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.heal]),
                            .init(name: "Fire Domain",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.buffAtk]),
                            .init(name: "Deadly Sword",
                                  power: 0,
                                  pp: 5,
                                  attributes: [.combo, .critical])
                         ])

let ALKI: Entity = .init(name: "Alki",
                         hp: 25,
                         atk: 0,
                         exa: 50,
                         def: 20,
                         spd: 5,
                         summon: nil,
                         money: 100,
                         item: [],
                         abilities: [
                            .init(name: "Culha",
                                  power: 1,
                                  pp: 10,
                                  attributes: [.heal]),
                            .init(name: "Drulha",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.drain]),
                            .init(name: "Trembo",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.buffAtk]),
                            .init(name: "Resfriado",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.nerfDef])
                         ])

let AMREN: Entity = .init(name: "Amren",
                         hp: 20,
                         atk: 0,
                         exa: 40,
                         def: 20,
                         spd: 10,
                         summon: nil,
                         money: 100,
                         item: [],
                         abilities: [
                            .init(name: "Shady Extension",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.buffAtk]),
                            .init(name: "Shadow Intangibility",
                                  power: 0,
                                  pp: 5,
                                  attributes: [.protect]),
                            .init(name: "Darkness Disorder",
                                  power: 0,
                                  pp: 5,
                                  attributes: [.nerfAtk, .nerfDef]),
                            .init(name: "Life Drain",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.drain])
                         ])

let VALAK: Entity = .init(name: "Valak",
                         hp: 20,
                         atk: 0,
                         exa: 20,
                         def: 20,
                         spd: 40,
                         summon: nil,
                         money: 100,
                         item: [],
                         abilities: [
                            .init(name: "Chupada",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.drain]),
                            .init(name: "Bomba de Sangue",
                                  power: 1,
                                  pp: 10,
                                  attributes: []),
                            .init(name: "Poça de Sangue",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.nerfDef]),
                            .init(name: "Petrificando Sangue",
                                  power: 0,
                                  pp: 5,
                                  attributes: [.protect])
                         ])

let YONIN: Entity = .init(name: "Yonin",
                         hp: 20,
                         atk: 50,
                         exa: 0,
                         def: 15,
                         spd: 15,
                         summon: nil,
                         money: 100,
                         item: [],
                         abilities: [
                            .init(name: "Relâmpago Marquinhos",
                                  power: 1,
                                  pp: 10,
                                  attributes: [.physical]),
                            .init(name: "Nichirin",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.buffDef]),
                            .init(name: "Fúria do Susano",
                                  power: 0,
                                  pp: 10,
                                  attributes: [.buffAtk]),
                            .init(name: "Passos Sombrios",
                                  power: 1,
                                  pp: 5,
                                  attributes: [.critical, .combo])
                         ])

var CHARACTERS: [Entity] = [ADELINE, ALKI, AMREN, VALAK, YONIN]
var ENEMIES = [Entity]()
